// examples/react-app/Checkout.tsx
export function Checkout() {
  return (
    <main>
      <h1>Checkout</h1>
      <h3>Payment</h3>
      <button>
        <CloseIcon />
      </button>
      <a>View receipt</a>
      <label>
        Email
        <input name="email" placeholder="name@example.com" />
      </label>
      <img src="/chart.png" />
      <div onClick={() => console.log("open")}>Open summary</div>
    </main>
  );
}

function CloseIcon() {
  return <svg aria-hidden="true" />;
}

// examples/scenario-fixtures/framework-matrix/src/vue/Checkout.vue
<template>
  <main>
    <button :aria-label="'Close cart'">
      <span aria-hidden="true">x</span>
    </button>
    <template #actions>
      <div @click="openPanel">Open panel</div>
    </template>
    <label :for="'email'">Email</label>
    <input :id="'email'" name="email" autocomplete="email">
  </main>
</template>

<script setup lang="ts">
const ignoredMarkup = "<button></button>";
function openPanel() {}
</script>
